### ISSUE TITLE
cURL file usage deprecated

### ISSUE THREAD

**Issue by vicentor** [podio-community/podio-php#101]
The usage of the @filename API for file uploading is deprecated. It suggests to use the CURLFile class instead.

Exemple: `$args['file'] = new CurlFile('test.html');`

**Comment by moerg** [comment]
Any update?

**Comment by daviferreira** [comment]
No update, PR welcome :)

**Comment by daniel-sc** [comment]
This should be resolved with v4.4.0 (see referenced PRs above). If not, please reopen!
