### ISSUE TITLE
Convert date to specified timezone

### ISSUE THREAD

**Issue by moerg** [podio-community/podio-php#103]
I try to convert a datetime object into a specified timezone (America/Montreal).

I use the latest Podio PHP library which is running on PHP 5.6.

Here's the code:
![code](https://cloud.githubusercontent.com/assets/10135983/10946597/11d4c9b8-82f1-11e5-801e-70e29da1ef0f.png)

I get that PHP error on script execution:
![error](https://cloud.githubusercontent.com/assets/10135983/10946610/282c558c-82f1-11e5-91b5-21c9f3b4584f.png)

Why is there microseconds on the datetime object?

Is there something wrong on my side? How could I handle timezone if I don't want Podio to change it to UTC and keep it as specified (America/Montreal)?

**Comment by vicentor** [comment]
It looks like the Podio library doesn't convert the DateTime object correctly. It could be a version incompatibility, but if so, it has to be fixed.
