### ISSUE TITLE
Fatal error on using composer with PodioItemField

### ISSUE THREAD

**Issue by irzhywau** [podio-community/podio-php#113]
Hi,

Here is the error

Fatal error: Cannot redeclare class PodioItemField in ~/project/vendor/podio/podio-php/models/PodioItemField.php on line 127

too many classes are declared in same file, how about separate each class declaration in other file else

**Comment by stechnique** [comment]
Same problem, been waiting several months for a reply
https://github.com/podio/podio-php/issues/111

**Comment by stechnique** [comment]
I just created a pull request that fixes the problem, hopefully merged soon.
Basically before every class definition inside the PodioItemField.php file I add a if(!class_exists...) statement.
