### ISSUE TITLE
Syntax Error!

### ISSUE THREAD

**Issue by kinged007** [podio-community/podio-php#117]
Hi,
I used to use this library, it worked. I try to use the latest version and I get the following error:
`Parse error: syntax error, unexpected 'return' (T_RETURN) in /var/www/vhosts/...../podio/vendor/podio-php-master/models/PodioItemField.php on line 605`

this comes up when I require the main api file:
`require_once 'vendor/podio-php-master/PodioAPI.php';`

Please help? I cant figure out why there is a syntax issue, I have run them through some syntax checkers online.

Thanks
Josh

**Comment by bajarang-agarwal** [comment]
@kinged007 I am not seeing any such issue. Do you still see this issue or it is resolved for you when you try the latest build?

**Comment by rafaelmb** [comment]
I think we should close this. It was created in 2016.
