### ISSUE TITLE
File upload doesn't work on PHP 5.6

### ISSUE THREAD

**Issue by moerg** [podio-community/podio-php#120]
I use PHP 5.6.19 and I try to upload a file to an item, I get the following error:

`PHP Fatal error:  Uncaught PodioBadRequestError: "'source' parameter must given as multipart/form-data with type 'file'"
Request URL: http://api.podio.com/file/v2/`

I tried with PHP 5.5 and it worked.

**Comment by marcelocecin** [comment]
same error with PHP 7.0.6-13

**Comment by hphuhtin** [comment]
See https://github.com/podio/podio-php/issues/74#issuecomment-77501868

**Comment by daniel-sc** [comment]
Closed as unactive, please reopen if problem persists.
