### ISSUE TITLE
Podio Api is not working (PHP) (podio-php-4.3.0)

### ISSUE THREAD

**Issue by sanjeevgehlot** [podio-community/podio-php#126]
I have downloaded the api setup from github and I installed it. It is working on one of my server but when I shifted to another server, it is not working.

I checked the code, and found on file podioAPI.php.

Code stops working after this below line.

require_once 'models/PodioItemField.php';

Please suggest..

**Comment by daniel-sc** [comment]
Please make sure to use podio-php via packagist: `composer require podio-community/podio-php && composer install` (see https://packagist.org/). If this does not resolve the issue, please reopen!
