### ISSUE TITLE
PodioItemField fails to handle fields of type 'tag' that exist in Contact-type Apps

### ISSUE THREAD

**Issue by hellokirk** [podio-community/podio-php#130]
Trying to get an $item->as_json(false) I discovered that it fails on contact apps, it ends up trying to call a generic PodioItemField->as_json(false) that doesn't exist.

I think we need to build a class for PodioTagItemField inside of PodioItemField.php; I'll work on that unless someone tells me there's a better way to handle this case...

**Comment by k1rked** [comment]
This should fix it: https://github.com/podio/podio-php/pull/131

**Comment by daniel-sc** [comment]
Hi @k1rked 

I'm taking this converstion from the PR (#131) back to this issue, to assure it is not lost once the PR is resolved.

As of https://developers.podio.com/doc/applications and as well when editing a contact app (see screenshot below) I cannot find a field of type 'tag':
![grafik](https://user-images.githubusercontent.com/117919/58765470-d43cd300-8573-11e9-9a1f-179733e7a7df.png)


Would you be able to hint how to create such an field or provide an example json that contains it?

**Comment by k1rked** [comment]
It's that organization field that can't be deleted, I believe:
