### ISSUE TITLE
First API Script - Need Help With Optimizing and Rate Limit Issues

### ISSUE THREAD

**Issue by jWright-Freelance** [podio-community/podio-php#133]
Just created my first PHP script implementing the Podio PHP library.  This script will run on the server via a cron job. I am getting the job done but I am running into a Rate Limit issue on the third or fourth instance of the script (it runs about every ten minutes).  Since this is my first attempt working with Podio I have no doubt I need to fix some bloated code problems.

The purpose of the script is to consume and parse an XML response from a remote URL call.  The data is then packaged up and used to create new items in a Podio Application.  As part of this process there are some remote image files which need to be grabbed and uploaded to the Podio Application Items.

Code sample:

// Podio API Library
require_once 'podio-php-4.3.0/PodioAPI.php';

// Podio connection
Podio::setup($client_id, $client_secret, array(
  "session_manager" => "PodioSession"
));

// Check if Podio already authenticated - does not work Podio re-authenticates each run of the script
if (!Podio::is_authenticated()) {
	echo "Re-Authenticated<br />";
	Podio::authenticate_with_app($app_id, $app_token);
}

class PodioBrowserSession {
	public function __construct() {
		if(!session_id()) {
			session_start();
		}
	}

	public function get($auth_type = null) {
		if (!empty($_SESSION['podio-php-session'])) {
			return new PodioOAuth(
				$_SESSION['podio-php-session']['access_token'],
				$_SESSION['podio-php-session']['refresh_token'],
				$_SESSION['podio-php-session']['expires_in'],
				$_SESSION['podio-php-session']['ref']
			);
		};
	}

	public function set($oauth, $auth_type = null) {
		$_SESSION['podio-php-session'] = array(
			'access_token' => $oauth->access_token,
			'refresh_token' => $oauth->refresh_token,
			'expires_in' => $oauth->expires_in,
			'ref' => $oauth->ref,
		);
	}
}

// Get all existing Podio webIDs (this is a UID field, this is needed to make sure that no duplicate entries are entered into Podio.  There is currently 130 entries, that number will grow fairly large over time.

$webIDs_list = array();
for ($i = 0; $i <= 100; $i++) {
	$offset = 200 * (int)$i;
	$collection = PodioItem::filter($app_id,array('limit'=>200,'offset'=>$offset));
	$webIDs_count = $collection->total;
	if ($webIDs_count > 0 ) {
		foreach ($collection as $item) {
			if (isset($item->fields['webid']->values)) {
				array_push($webIDs_list,strip_tags($item->fields['webid']->values));
			}	
		}
	}
	else {
		break;
	}
}

<<XML Magic happens here>>

$i = 0;
foreach ($acme_listing as $webID => $listing_data) {
	// Skip blank webIDs or webIDs already in Podio
	if ($webID == '' || in_array($webID, $webIDs_list)) continue;
	// About 10 entries at a time else the script will time out due to image downloads and uploads
	$i++;
	if ($i > 10) break;
	// Create a field collection with some fields.
	$fields = new PodioItemFieldCollection(array(
		new PodioTextItemField(array("external_id" => "webid", "values" => "$webID"))
	));	

        // $listing_data is an array that holds all the XML data gathered earlier
	foreach ($listing_data AS $field => $value) {
		// Skip any listings with incomplete data
		if ($field == '' || $value == '') continue;
		if ($field === 'xxx') {
			// Location Field
			$itemfield = new PodioLocationItemField(array("external_id" => $field, "values" => $value));
		}
		else if ($field === 'xxx' ||
		$field === 'xxx' ) {
			// Category Field
			$itemfield = new PodioCategoryItemField(array("external_id" => $field, "values" => $value));
		}
		else if ($field === 'xxx') {
			// Money Field
			$itemfield = new PodioMoneyItemField(array("external_id" => $field, "values" => floatval(preg_replace('/[\$,]/','', $value))));
		}
		else if ($field === 'photo') {
			// Image Field
			foreach ($value AS $this_url){
				// Get image files from Acme
				$img_url = trim($this_url);
				$ext = pathinfo($img_url, PATHINFO_EXTENSION);
                                // itg_fetch_image is a function that will fetch a remote image file and store it on the local server and return the path to the local copy
				$image_file = itg_fetch_image($img_url,'midbrook_tmp','relative');
				if ($image_file != '') {
					// Upload file to Podio
					$imgfile = PodioFile::upload($image_file,basename($image_file));
					$itemfield = new PodioImageItemField(array("external_id" => $field, "values" => $imgfile));
					
					// Clean house
					unlink($image_file);
				}
			}
		}
		else if ($field === 'xxx' || 
		$field === 'xxx' ) {
			// Date field
			$itemfield = new PodioDateItemField(array("external_id" => $field));
			if ($field === 'xxx') {
				$l_val = $value;
			}
			elseif ($field === 'xxx') {
				$m_val = $value;
			}
			else {
				$last_updated_val = $value;
			}
		}
		else if ($field === 'xxx') {
			// Embed field
			// Create embed
			$embed = PodioEmbed::create(array('url' => $value));
			$itemfield = new PodioEmbedItemField(array("external_id" => $field, "values" => $embed));
		}
		else {
			// Text field
			$itemfield = new PodioTextItemField(array("external_id" => $field, "values" => $value));
		}
		$fields[] = $itemfield;
	}

	// Create the item object with fields
	$item = new PodioItem(array(
	  'app' => new PodioApp($app_id),
	  'fields' => $fields
	));
	
	// Attach date
    $item->fields['listed-on']->start_date = $l_val;
	$item->fields['move-in-date']->start_date = $m_val;
	$item->fields['last-updated']->start_date = $last_updated_val;

	// Save the new item
	$item->save();
}

And there you have it.  It takes the script about 4 minutes to run each iteration of itself.

Thanks!

**Comment by hphuhtin** [comment]
API programming discussion should be posted to stackoverflow with tag Podio, not GitHub.
