### ISSUE TITLE
composer dependency ad dependcy

### ISSUE THREAD

**Issue by Grummfy** [podio-community/podio-php#135]
hello,
I see a vendor directory in lib. And in this we clearly see a composer dependency. You can make it explicit in the composer.json of this project. 

If the purpose of this is to create independent zip file for people without composer, you can create release in github with the help of composer there is a lot of solutions, including a native one https://getcomposer.org/doc/03-cli.md#archive

**Comment by viewfromthenorth** [comment]
I second this as a major issue. There probably shouldn't be a /vendor directory anywhere in this project.

I am trying to install the podio-php library using composer in a project using Codeigniter 4, which already includes Kint, and it's causing 500 errors that I can't get around.
