### ISSUE TITLE
Create an up-to-date release

### ISSUE THREAD

**Issue by benk-cogapp** [podio-community/podio-php#145]
Could we please have a new release added containing the latest code. It appears the last release (4.3.0) is from 2015 which means that, when installing via composer, there are bugs present which don't exist in the latest code from master. As an example, I ran into #74/#120 which is now fixed in [`PodioFile::upload`](https://github.com/podio/podio-php/blob/master/models/PodioFile.php#L53) on master.

As an interim fix for anyone wanting to use composer with the latest code, I updated my composer.json with:

```
composer require podio/podio-php:dev-master
```

Which points at the latest version on master rather than the latest release.

**Comment by daniel-sc** [comment]
Just released [4.4.0](https://github.com/podio-community/podio-php/releases/tag/v4.4.0)
