### ISSUE TITLE
Filter API missing file_count parameter

### ISSUE THREAD

**Issue by bajarang-agarwal** [podio-community/podio-php#151]
Filter Item API returns 'file_count' attribute as a result response but the current library is missing this data. Here is the URL for API Detail:
https://developers.podio.com/doc/items/filter-items-4496747

I am opening a ticket to submit the pull request for this issue.

**Comment by daniel-sc** [comment]
Hi @bajarang-agarwal,

your fix looks good - would you like to create a PR from this? If you need any help, let me know!

**Comment by bajarang-agarwal** [comment]
@daniel-sc If I understand correctly, you are looking for PR link: 
https://github.com/podio-community/podio-php/pull/152

**Comment by bajarang-agarwal** [comment]
@daniel-sc I am sorry to ask you a novice question. Is it okay to close this issue as we already merged the fix for this OR we close the ticket later?

**Comment by daniel-sc** [comment]
Hi @bajarang-agarwal 
this is actually not really defined yet. I'd suggest we generally close issues when the PR is merged - this allows to auto close issues when merging PRs. If you think otherwise would be better, please share!
