### ISSUE TITLE
Maintain community fork

### ISSUE THREAD

**Issue by daniel-sc** [podio-community/podio-php#153]
Hello everyone,

as there are quite some people that actively use this PHP Podio client and this repo is not officially maintained any more, I'd suggest to create a community fork. Anyone motivated to step forward as maintainer? 

*hoping for feedback*

Daniel

**Comment by daniel-sc** [comment]
@bajarang-agarwal @timosillander @rafaelmb @carlfredrikhero @jackparnell @jeff-goodman @benk-cogapp @daviferreira 

anyone interested in maintaining a community fork?

(I just added active people I found in issues/PRs from 2018 here, please feel free to add more potential maintainer/contributors!)

**Comment by rafaelmb** [comment]
I definitely can help

**Comment by bajarang-agarwal** [comment]
I am also happy to help and maintaining community fork

**Comment by carlfredrikhero** [comment]
I would really like to see a community fork!

**Comment by timosillander** [comment]
I only just noticed the No Maintenance Intended badge on Podio PHP client. Damn.
I too would love to see a community fork. Not much of a coder, so not sure how much I'd be of help, mind.

**Comment by daniel-sc** [comment]
Ok - anyone stepping forward to get this going?
If not, I can do it, but that might be slow paced.. ;-)

**Comment by daniel-sc** [comment]
@cmchase I see you were the last one maintaining this repository - would it be possible to transfer this repository to the new [podio-commmunity](https://github.com/podio-community) organization I created, so that we can maintain this php client there? Alternatively we could as well simply fork this repo, but this would mean loosing all PRs and issues and you'd need to add a reference to the community project to be well visible in the readme (a community fork that no one knows of is probably not much help..). There is some interest in a community fork - see the comments above in this issue - so it would be really cool if you could help us kicking it off!

Let me know what you think!

See: https://help.github.com/en/articles/transferring-a-repository

**Comment by jakemwp** [comment]
I'd be happy to help maintain a community fork. I have some rough custom functions I've built on top of the existing PHP client, so feel free to reach out if this gets off the ground.

**Comment by npphases** [comment]
I'm happy to help since I have been using this wrapper from the beginning of its development.

**Comment by dylannadon** [comment]
Hi @daniel-sc et al,
We are discussing this internally and will get back to you.

**Comment by dylannadon** [comment]
Hi @daniel-sc we will transfer this repo to the Podio Community organization. Could you please add me to the organization with create repo permissions?

**Comment by daniel-sc** [comment]
Hi @dylannadon, thanks for deciding on this. I invited you to the org. If there is something else you need for this please let me know.

**Comment by dylannadon** [comment]
Done!

**Comment by ubani** [comment]
happy to help, too.

**Comment by bajarang-agarwal** [comment]
Thanks @dylannadon 

@daniel-sc Thank you for taking this initiative and we can see a lot of people are interested to help to maintain this.

**Comment by daniel-sc** [comment]
Ok - the transfer is completed (big thanks @dylannadon !) so I'll close this issue. Thanks everyone for your offered help and support!
For discussions about (updated) contribution guidlines and other stuff, we should create new issues/PRs.
