### ISSUE TITLE
Revival and batch operations

### ISSUE THREAD

**Issue by vicentor** [podio-community/podio-php#156]
First, we're happy to see a potential revival of the Podio API. It's obvious (in our opinion) that Podio does not have any in-house full-time developers anymore. Our whole company uses the API extensively and will try our best to provide tweaks when able. We just really wanted to mention this. **How can we access the Podio PHP (basic) documentation? (previously here: http://podio.github.io/podio-php)**

Also, we have clients using Podio intensively and they often break the API limit. We contacted the Podio support a few times and while they may increase the limit in a certain context, we wanted to know if anyone has been able to use the "batch" features (I can't link to the related due to the previous problem documentation).

As an example, if we wanted to get 30 items with all its details, we would have to call 30x `PodioItem::get` since `PodioItem::filter` returns limited information.

Assuming we have the item IDs, does anyone know if we can merge it into 1 call (instead of 30)? Something like `PodioItem::get(array(item_id1, item_id2, item_id3));`

**Comment by daniel-sc** [comment]
Hi @vicentor 

the documentation url changed to: http://podio-community.github.io/podio-php/ (will be updated soon on the readme..)

Not really sure what you mean by teh "batch" features.. do you refer to https://developers.podio.com/doc/batch/ ? This only describes read access..

Regarding the fetching of multiple items with more details, you might want to check the "Bundling responses using fields parameter" section on https://developers.podio.com/index/api . This should be applied using the PHP client like this: `PodioItem::filter(APP_ID, ['fields' => 'full'])` (not sure about the actual format - if you find out more details please post it here :)

Does this resolve youre questions?

**Comment by magikweb** [comment]
Thanks for the follow-up!

You're helping for sure.
We were referring to the bundling responses thinking that the _filter_ operation didn't return much. After validating, it returns everything we need for our current context.

It doesn't return the file IDs, but we don't need them for now.

As vague as our question was, you resolved it. d('-')b

**Comment by carlfredrikhero** [comment]
@magikweb Does this mean we can close the issue?

**Comment by vicentor** [comment]
Yes, you may close it! (I can't seem to be able to)
