### ISSUE TITLE
get_count for view?

### ISSUE THREAD

**Issue by gailmichi** [podio-community/podio-php#159]
Hi there, 

i´m trying to get the count of items of a specific view.
I used this code but it doesn´t work:

 `$count = PodioItem::get_count($app_id,41426040);`

I always get the number of all items in the app, not for the view.
In podio sandbox it´s working fine with my view_id (41426040).

How do i have to set the view_id parameter as described in the api-reference?

Thank you very much.
Mike

**Comment by daniel-sc** [comment]
Hi @gailmichi 

this is not yet implemented in the php client.
Would you be motivated to create a PR for this?

As a workaround you should be able to use: 

```
Podio::get("/item/app/{$app_id}/count", ["view_id" => $view_id])
``` 

Best, Daniel

**Comment by rafaelmb** [comment]
I'm trying to do this but I can't figure it out what to do with the method signature. 

Docs point to app_id (that our method have) {key} and view_id

Any suggestion @daniel-sc

**Comment by daniel-sc** [comment]
Hi @rafaelmb 

I'd suggest something like the following in `PodioItem`:

```php
  public static function get_count($app_id, $view_id = null) {
    $attributes = empty($view_id) ?  array() : array("view_id" => $view_id);
    $body = Podio::get("/item/app/{$app_id}/count", $attributes)->json_body();
    return $body['count'];
  }
```
This should of course be tested etc...
