### ISSUE TITLE
Missing options field in PodioItemDiff::get_for

### ISSUE THREAD

**Issue by rafaelmb** [podio-community/podio-php#163]
Hi, 

I was messing around my podio this week and found a bug in the PodioItemDiff::get_for, where the item with difference does not come with the options field, like when we fetch the json from Podio service. I found the line that should be fixed and I'm making the pull request, I was just wondering if anyone has the same issue.

**Comment by carlfredrikhero** [comment]
I verified with the sandbox operation that a config key is present in the response:

```
"config": {
      "default_value": null,
      "unique": false,
      "description": null,
      "hidden_create_view_edit": false,
      "required": false,
      "mapping": null,
      "label": "Ska",
      "visible": true,
      "delta": 2,
      "hidden": false,
      "settings": {
        "format": "html",
        "size": "large"
      }
``` 

Good job, thanks!
