### ISSUE TITLE
New release / package name

### ISSUE THREAD

**Issue by daniel-sc** [podio-community/podio-php#165]
Hi @dylannadon,

to create a new release under the same package name (https://packagist.org/packages/podio/podio-php) we'd need maintainer access to the corresponding composer vendor. Would it be possible to get me (or someone else) this access level? Or would you prefer us to release under a different name (e.g. `podio-community/podio-php`)?

@all: What would the other contributers prefer?

**Comment by carlfredrikhero** [comment]
I would prefer to release it under the podio-community prefix. For clarity.

**Comment by rafaelmb** [comment]
I agree that it should change to podio-community as we are not a part  of Podio. But I keep thinking about how composer would behave for older users, probably nothing bad since people rarely update something.

**Comment by dylannadon** [comment]
Agreed, please release under a different name.

**Comment by daniel-sc** [comment]
Ok, I created a PR for the updated vendor name. Once this is reviewed + merged, I'll cut a first release `4.4.0`.

**Comment by daniel-sc** [comment]
just released 4.4.0 :)
