### ISSUE TITLE
Helper Libraries

### ISSUE THREAD

**Issue by rafaelmb** [podio-community/podio-php#175]
Hi people, how are you today?

A few months ago I found out that one of the laravel services to connect with podio  spotonlive/laravel-podio was using the old podio/podio-php and I did a pull request to them that have not been merged yet. Knowing how opensource works of course they have no obligation so, I am willing to fork and maintain the library but I was wondering if I could or should do this under podio-community ?

Any thoughts?

**Comment by daniel-sc** [comment]
If I understand correctly this is more like a Laravel _Plugin_ that is _using_ the podio-php lib - correct?
In this case I'd not include this under podio-community, but maintain it seperately - maybe together with other laravel plugins?

**Comment by rafaelmb** [comment]
You are correct. I was hoping to get a new set of eyes on this fork but even here is usually just you and me. I will close this now.
