### ISSUE TITLE
Update documentation 

### ISSUE THREAD

**Issue by daniel-sc** [podio-community/podio-php#177]
Documentation is rather out of date..

Should we remove it and just have a minimal instruction in readme.md or keep it updated?

**Comment by rafaelmb** [comment]
Hi Daniel, which documentation are you talking about? I may take a look and update it since I am trying to get more confortable with  the Podio API.

**Comment by daniel-sc** [comment]
Hi @rafaelmb  - cool - I was referring to https://podio-community.github.io/podio-php/ this is build from the `gh-pages` branch.
