### ISSUE TITLE
Search in app v2 - Nothing is returned

### ISSUE THREAD

**Issue by heisenberg41** [podio-community/podio-php#184]
**Problem**
I am using https://developers.podio.com/doc/search/search-in-application-v2-155196220. For some reason it isn't returning a value.

**What I Tried**

- I tested to make sure all the variables are populating appropriately and that it is authenticating. 
- Other API calls like PodioItem::get_basic are working for me.
- I added Podio::set_debug(true); before the API call but it doesn't seem to be outputting anything to the screen, console. or php error log.

**What I'm Trying to Do**

Ultimately, I need the specific item id so I can update some fields within the item. Thanks in advance for your help.

```
	       Podio::set_debug(true);
               Podio::setup($this->client_id, $this->client_secret);
        
		try {
		    Podio::authenticate_with_password($this->username, $this->password);
		    $lead_item = PodioSearchResult::app(6330134, $attributes = array(
	                 'query' => $client_name, 
		         'ref_type' => 'item'));
	            echo $lead_item->id;
		
		    /*
		    $item = PodioItem::get_basic($lead_item->item_id);
		    $item->fields["category"]->values = 7;   //Lead Status -> Paperwork RECEIVED
		    $item->fields["paperwork-received"]->values = 1;  //Paperwork RECEIVED -> Yes
		    $item->fields["category-2"]->values = 3;   //Category - > Client
		    $item->save();
		    */
		}

		catch (PodioError $e) {echo $e->body['error_description'];}
```

**Comment by daniel-sc** [comment]
Hi @heisenberg41 ,

to analyse this, we'd need some more details:

* what exactly is the output/error?
* which PHP version?
* which podio-php version?
* running via CLI or a (which?) webserver?

**Comment by heisenberg41** [comment]
Hi @daniel-sc ,

- Output/error - There is none, which is making it hard to trouble shoot.  Nothing shows in the console, no errors in php error log, and nothing displays on the screen.
- PHP version 7.3
- podio-php-4.4.0
- running via cloud linux 7.7 web server

The item that I am searching for in Podio is there.  If I use Podio's sandbox with the same parameters, the item returns just fine.

I've echoed all the variables prior to the PodioSearchResult::app call.  Everything looks good.  Triple double checked the app id.  

I did a var_dump on $lead_item and it seems that PodioSearchResult::app is returning the item (see below).  

I also tried print_r($lead_item->properties()); but that gives me a PHP error: PHP Fatal error:  Uncaught Error: Call to a member function properties() on array in print_r($lead_item->properties());

Shouldn't PodioSearchResult::app return an object as opposed to an array?

`array(1) { [0]=> object(PodioSearchResult)#5 (5) { ["__attributes":"PodioObject":private]=> array(10) { ["id"]=> int(1360477711) ["type"]=> string(4) "item" ["rank"]=> NULL ["title"]=> string(9) "Matt Test" ["created_on"]=> string(19) "2020-03-05 20:57:13" ["link"]=> string(81) "https://podio.com/inception-websitescom/new-client-start-up/apps/leads/items/5869" ["app"]=> array(14) { ["status"]=> string(6) "active" ["sharefile_vault_url"]=> NULL ["default_view_id"]=> NULL ["url_label"]=> string(5) "leads" ["item_accounting_info"]=> NULL ["link_add"]=> string(80) "https://podio.com/inception-websitescom/new-client-start-up/apps/leads/items/new" ["app_id"]=> int(6330134) ["current_revision"]=> int(164) ["is_default"]=> bool(false) ["url"]=> string(70) "https://podio.com/inception-websitescom/new-client-start-up/apps/leads" ["link"]=> string(70) "https://podio.com/inception-websitescom/new-client-start-up/apps/leads" ["config"]=> array(10) { ["allow_edit"]=> bool(true) ["description"]=> string(0) "" ["item_name"]=> string(4) "Lead" ["external_id"]=> NULL ["icon_id"]=> int(217) ["allow_create"]=> bool(true) ["usage"]=> string(0) "" ["icon"]=> string(7) "217.png" ["type"]=> string(8) "standard" ["name"]=> string(5) "Leads" } ["url_add"]=> string(80) "https://podio.com/inception-websitescom/new-client-start-up/apps/leads/items/new" ["space_id"]=> int(1613794) } ["org"]=> array(14) { ["premium"]=> bool(true) ["status"]=> string(6) "active" ["contract_status"]=> string(4) "full" ["name"]=> string(26) "Inception Online Marketing" ["url"]=> string(39) "https://podio.com/inception-websitescom" ["type"]=> string(7) "premium" ["image"]=> array(7) { ["hosted_by"]=> string(5) "podio" ["hosted_by_humanized_name"]=> string(5) "Podio" ["thumbnail_link"]=> string(53) "https://d2cmuesa4snpwn.cloudfront.net/public/61029064" ["link"]=> string(53) "https://d2cmuesa4snpwn.cloudfront.net/public/61029064" ["file_id"]=> int(61029064) ["external_file_id"]=> NULL ["link_target"]=> string(6) "_blank" } ["org_id"]=> int(475801) ["tier"]=> string(7) "premium" ["url_label"]=> string(21) "inception-websitescom" ["domains"]=> array(1) { [0]=> string(22) "inception-websites.com" } ["logo"]=> int(61029064) ["segment"]=> NULL ["segment_size"]=> int(1) } ["space"]=> array(8) { ["sharefile_vault_url"]=> NULL ["name"]=> string(22) "2.ESSENTIALS WORKSPACE" ["url"]=> string(59) "https://podio.com/inception-websitescom/new-client-start-up" ["url_label"]=> string(19) "new-client-start-up" ["item_accounting_info"]=> NULL ["org_id"]=> int(475801) ["type"]=> string(7) "regular" ["space_id"]=> int(1613794) } ["created_by"]=> object(PodioByLine)#6 (5) { ["__attributes":"PodioObject":private]=> array(8) { ["type"]=> string(4) "user" ["id"]=> int(4619631) ["avatar_type"]=> string(4) "file" ["avatar_id"]=> int(1028171148) ["image"]=> array(7) { ["hosted_by"]=> string(5) "podio" ["hosted_by_humanized_name"]=> string(5) "Podio" ["thumbnail_link"]=> string(55) "https://d2cmuesa4snpwn.cloudfront.net/public/1028171148" ["link"]=> string(55) "https://d2cmuesa4snpwn.cloudfront.net/public/1028171148" ["file_id"]=> int(1028171148) ["external_file_id"]=> NULL ["link_target"]=> string(6) "_blank" } ["name"]=> string(12) "Matt" ["url"]=> string(31) "https://podio.com/users/4619631" ["avatar"]=> int(1028171148) } ["__belongs_to":"PodioObject":private]=> array(2) { ["property"]=> string(10) "created_by" ["instance"]=> *RECURSION* } ["__properties":"PodioObject":private]=> array(8) { ["type"]=> array(2) { ["type"]=> string(6) "string" ["options"]=> array(0) { } } ["id"]=> array(2) { ["type"]=> string(7) "integer" ["options"]=> array(0) { } } ["avatar_type"]=> array(2) { ["type"]=> string(6) "string" ["options"]=> array(0) { } } ["avatar_id"]=> array(2) { ["type"]=> string(7) "integer" ["options"]=> array(0) { } } ["image"]=> array(2) { ["type"]=> string(4) "hash" ["options"]=> array(0) { } } ["name"]=> array(2) { ["type"]=> string(6) "string" ["options"]=> array(0) { } } ["url"]=> array(2) { ["type"]=> string(6) "string" ["options"]=> array(0) { } } ["avatar"]=> array(2) { ["type"]=> string(7) "integer" ["options"]=> array(0) { } } } ["__relationships":"PodioObject":private]=> array(0) { } ["__id_column":protected]=> NULL } } ["__belongs_to":"PodioObject":private]=> NULL ["__properties":"PodioObject":private]=> array(10) { ["id"]=> array(2) { ["type"]=> string(7) "integer" ["options"]=> array(0) { } } ["type"]=> array(2) { ["type"]=> string(6) "string" ["options"]=> array(0) { } } ["rank"]=> array(2) { ["type"]=> string(7) "integer" ["options"]=> array(0) { } } ["title"]=> array(2) { ["type"]=> string(6) "string" ["options"]=> array(0) { } } ["created_on"]=> array(2) { ["type"]=> string(8) "datetime" ["options"]=> array(0) { } } ["link"]=> array(2) { ["type"]=> string(6) "string" ["options"]=> array(0) { } } ["app"]=> array(2) { ["type"]=> string(4) "hash" ["options"]=> array(0) { } } ["org"]=> array(2) { ["type"]=> string(4) "hash" ["options"]=> array(0) { } } ["space"]=> array(2) { ["type"]=> string(4) "hash" ["options"]=> array(0) { } } ["created_by"]=> array(2) { ["type"]=> string(6) "ByLine" ["options"]=> array(0) { } } } ["__relationships":"PodioObject":private]=> array(1) { ["created_by"]=> string(7) "has_one" } ["__id_column":protected]=> NULL } }`

**Comment by daniel-sc** [comment]
Hi @heisenberg41,

the cause of the problem is that `PodioSearchResult::app` does not return a (single) item but a list/collection of items - so if you'd try `$lead_item[0]->id` you should get the id of the first result.

Regarding the debug option: If working in a non-cli setup (i.e. a webserver), you'd need to set it up with `Podio::set_debug(true, 'file')`, then there should be a file `log/podio.log` created with the debug output. See as well the (not completely correct) docs: https://podio-community.github.io/podio-php/debug/

Please reopen if this does not resolve your issue!

Best, Daniel
