### ISSUE TITLE
Email, Phone and Number Type Podio item field showing blank after creation of item by api

### ISSUE THREAD

**Issue by ranjan006** [podio-community/podio-php#186]
I am creating Item by api. Item is creating but email, phone and number type field not storing value. It is showing blank in podio account. here is my code:

// !!! this is an example, it depends form fields in your form
//$num = 4301.00;
$first = $form_fields[ 1 ][ 'value' ];
$last = $form_fields[ 2 ][ 'value' ];
//$email = $form_fields[ 3 ][ 'value' ];
//$phone = $form_fields[ 4 ][ 'value' ];

$fields = new PodioItemFieldCollection(array(
new PodioTextItemField(array("external_id" => "name", "values" => $first)),
new PodioTextItemField(array("external_id" => "efternavn", "values" => $last))
));

// Create the item object with fields
// Be sure to add an app or podio-php won't know where to create the item
$item = new PodioItem(array(
'app' => new PodioApp(23258136), // Attach to app with app_id=123
'fields' => $fields
));

$number_field_id = 'lead-nummer';
$email_field_id = 'email-address';
$phone_field_id = 'phone-number';

$item->fields[$number_field_id]->values = "4301.00";
$item->fields[$email_field_id]->values = array('value'=>"i@oooo.com",'type'=>'work');
$item->fields[$phone_field_id]->values = array('value'=>"7044636740",'type'=>'work');

// Save the new item
$item->save();

**Comment by rafaelmb** [comment]
Hello @ranjan006 does your request return any message at all?

One thing that caught my attention is that the fields that look ok on podio were created using the sdk (podio fields and collections) and the items with arrays didn't work? If thats the case you should try using only one method. In my project we use only arrays.

**Comment by ranjan006** [comment]
Nothing return. Item with array did not work that's why i have used another method for number, email and phone type field.

Actually, I am using api in wordpress with ninja form. Everything is working but number, email and phone field type is not working.

**Comment by ranjan006** [comment]
I am getting error:-

 Uncaught Error: Class 'PodioPhoneOrEmailItemField' not found in /var/www/www.spi.dk/www/wp-content/plugins/podio-api-for-wordpress-master/_/Podio/models/field/PodioEmailItemField.php:6

**Comment by rafaelmb** [comment]
I don't know what "podio api for wordpress" is, but looks like another library.

**Comment by daniel-sc** [comment]
@ranjan006 is it possible that you use https://github.com/rodrigoescandon/podio-api-for-wordpress and not this lib? The WP thing looks rather old and unmaintained..

**Comment by daniel-sc** [comment]
Ok - could you please post the exact code leading to this error?

**Comment by ranjan006** [comment]
It's ok. Now it is solved. Thanks to all.
