### ISSUE TITLE
podio api session 

### ISSUE THREAD

**Issue by mehermakloufi** [podio-community/podio-php#188]
I fetch the list of items from the podio and the process succeeds but when I reload the page this error appears : 'PodioAuthorizationError'

the code is : 

`
\Podio::setup($client_id, $client_secre);

           if (\Podio::is_authenticated()) {

           }else{

               try {

                   \Podio::authenticate('app', array('app_id' => $app_id, 'app_token' => $app_token));

               } catch (PodioError $e) {

               }

           }
`
` 

         // get all items :

          $test = \PodioItem::filter($app_id, array(

                    'limit' => 100,

                    'sort_by' => 'created_on'));

          return $test;
`

I searched in google and found someone talking about a problem in session podio api but i dont know how the solution is.

**Comment by daniel-sc** [comment]
Could you try to use latest version „dev-master“ and set debug output? And check what the actual requests are?

**Comment by daniel-sc** [comment]
Closed as stale. Reopen if this persists.
