### ISSUE TITLE
Podio API PHP PodioItem not updating when relationship type field is empty

### ISSUE THREAD

**Issue by caribesoft** [podio-community/podio-php#195]
I have been struggled with my PHP script, I need to update a relationship type item in a app with Podio API php. Whe the field is "blank", does no work, I mean does not update the field, when it has a value it works, the item is modified with the new value, here is part of my code:

`$item = PodioItem::get_basic($itemId);
    $field_id = 'last-action-by';
    $item->fields[$field_id]->values = array('item_id' => $contacto);
    $item->save();`

In advance thank you for your help!

**Comment by daniel-sc** [comment]
Hi @caribesoft 

did you try something like the following (see "Add field" in https://podio-community.github.io/podio-php/items/):

```php
$item = PodioItem::get($itemId); // get_basic is deprecated
$field_id = 'last-action-by'; 
$item->fields[] = new PodioAppItemField(['external_id' => $field_id, 'values' => ['item_id' => $contacto]]); 
$item->save();
```

(Which version of PHP and podio-php are you on?)

**Comment by caribesoft** [comment]
Hi Daniel, thank you for your comment, yes I tried something like the example on the link, the problem was I was passing on the $contacto variable, an email and it shoud be the contact_id as integer, and it works now!, again thank you!
