### ISSUE TITLE
POST request throws PodioBadRequestError with valid input, did API change in the last 6 months?

### ISSUE THREAD

**Issue by johnBHGW** [podio-community/podio-php#198]
I support a small Podio <--> Silverstripe-CMS integration for a company that has been using Podio in the same way for about 2 1/2 years. They mainly use it to track client and account leads that come from their website. 
   About 6 months ago I was asked to programmatically select a tag and add it to each new lead that they create.  So I looked at their fields returned from a Postman call to GET /app/{app_id}/item/{app_item_id}. Specifically the id's of the individual tags in their collection of tags(tags-2).  I added that id to every lead created where that tag was present in the tag collection and it worked without a problem.  A couple of weeks ago I was asked to add another so I followed the same approach and I keep getting the PodioBadRequestError and the lead creation fails. Did the API change without my knowing it? The documentation looks about the same as it did before so I don't see where things may have changed that much. 
   Could there have been changes made to the way that this client is interacting with the items, or maybe I am not doing it correctly in the first place?  I will include a few lines of code in case it's something that is potentially an issue, otherwise if it looks like my stupid go ahead and kill the issue.

Here is how I am creating the $item and then adding the tag_id's to it:

            $item = [
            'fields' => [
                'name'          => $this->PrimaryContactFirstName,
                'last-name'     => $this->PrimaryContactLastName,
                'email-address' => ['type' => 'work', 'value' => $this->PrimaryContactEmail],
                'phone-number'  => ['type' => 'work', 'value' => $this->PrimaryContactPhone],
                'address'       => $address,
                'organization'  => [$this->CompanyName],
                'tags-2' => []
            ],
        ];

Here is where I am adding the tag_id's:  The first one(NEWSLETTER) worked, the second one(ORG_TYPE) errors out

             if ($this->Newsletter && defined('PODIO_NEWSLETTER_TAG_ID')) {
            $item['fields']['tags-2'][] = PODIO_NEWSLETTER_TAG_ID;
        }

        if($this->OrganizationType && defined('PODIO_ORGANIZATION_TYPE_ID')){
            //check the Org type, add the appropriate ID to the tags-2 array
            if($this->OrganizationType == "Clinic"){
                $item['fields']['tags-2'][] = PODIO_ORGANIZATION_TYPE_CLINIC_TAG_ID;
            }
            else if($this->OrganizationType == "Hospital"){
                $item['fields']['tags-2'][] = PODIO_ORGANIZATION_TYPE_HOSPITAL_TAG_ID;
            }
            else if($this->OrganizationType == "Surgery Center"){
                $item['fields']['tags-2'][] = PODIO_ORGANIZATION_TYPE_SURGERY_TAG_ID;
            }
        }

Here is where I am creating the Lead:

    $customerLead = PodioItem::create(PODIO_CUSTOMER_APP_ID, $item);

Here is the error messages from the php.log file with debug turned on.

```
28-Oct-2020 16:33:51 America/New_York] Encountered error while adding AccountLead to Podio: PodioBadRequestError: "Invalid value 97 (integer): Not a valid option"
Request URL: http://api.podio.com/item/app/23000000007/

Stack Trace:
#0 /Users/bhg/Documents/repos/my_application_name/vendor/podio/podio-php/lib/Podio.php(354): Podio::request('POST', '/item/app/23068...', Array, Array)
#1 /Users/bhg/Documents/repos/my_application_name/vendor/podio/podio-php/models/PodioItem.php(167): Podio::post('/item/app/23068...', Array)
#2 /Users/bhg/Documents/repos/my_application_name/mysite/code/AccountLead.php(309): PodioItem::create('23068007', Array)
#3 /Users/bhg/Documents/repos/my_application_name/betterbuttons/code/extensions/GridFieldBetterButtonsItemRequest.php(674): AccountLead->addToPodio(Object(BetterButtonCustomAction), Object(GridFieldDetailForm_ItemRequest), Object(SS_HTTPRequest))
#4 /Users/bhg/Documents/repos/my_application_name/framework/control/RequestHandler.php(288): BetterButtonsCustomActionRequest->handleCustomAction(Object(SS_HTTPRequest))
#5 /Users/bhg/Documents/repos/my_application_name/framework/control/RequestHandler.php(200): RequestHandler->handleAction(Object(SS_HTTPRequest), 'handleCustomAct...')
#6 /Users/bhg/Documents/repos/my_application_name/betterbuttons/code/extensions/GridFieldBetterButtonsItemRequest.php(53): RequestHandler->handleRequest(Object(SS_HTTPRequest), Object(DataModel))
#7 [internal function]: GridFieldBetterButtonsItemRequest->customaction(Object(SS_HTTPRequest))
#8 /Users/bhg/Documents/repos/my_application_name/framework/core/Object.php(749): call_user_func_array(Array, Array)
#9 /Users/bhg/Documents/repos/my_application_name/framework/control/RequestHandler.php(288): Object->__call('customaction', Array)
#10 /Users/bhg/Documents/repos/my_application_name/framework/control/RequestHandler.php(288): GridFieldDetailForm_ItemRequest->customaction(Object(SS_HTTPRequest))
#11 /Users/bhg/Documents/repos/my_application_name/framework/control/RequestHandler.php(200): RequestHandler->handleAction(Object(SS_HTTPRequest), 'customaction')
#12 /Users/bhg/Documents/repos/my_application_name/framework/forms/gridfield/GridFieldDetailForm.php(102): RequestHandler->handleRequest(Object(SS_HTTPRequest), Object(DataModel))
#13 /Users/bhg/Documents/repos/my_application_name/framework/forms/gridfield/GridField.php(983): GridFieldDetailForm->handleItem(Object(PersistentGridField), Object(SS_HTTPRequest))
#14 /Users/bhg/Documents/repos/my_application_name/framework/control/RequestHandler.php(222): GridField->handleRequest(Object(SS_HTTPRequest), Object(DataModel))
#15 /Users/bhg/Documents/repos/my_application_name/framework/control/RequestHandler.php(222): RequestHandler->handleRequest(Object(SS_HTTPRequest), Object(DataModel))
#16 /Users/bhg/Documents/repos/my_application_name/framework/control/Controller.php(158): RequestHandler->handleRequest(Object(SS_HTTPRequest), Object(DataModel))
#17 /Users/bhg/Documents/repos/my_application_name/framework/admin/code/LeftAndMain.php(464): Controller->handleRequest(Object(SS_HTTPRequest), Object(DataModel))
#18 /Users/bhg/Documents/repos/my_application_name/framework/admin/code/AdminRootController.php(92): LeftAndMain->handleRequest(Object(SS_HTTPRequest), Object(DataModel))
#19 /Users/bhg/Documents/repos/my_application_name/framework/control/Director.php(385): AdminRootController->handleRequest(Object(SS_HTTPRequest), Object(DataModel))
#20 /Users/bhg/Documents/repos/my_application_name/framework/control/Director.php(149): Director::handleRequest(Object(SS_HTTPRequest), Object(Session), Object(DataModel))
#21 /Users/bhg/Documents/repos/my_application_name/framework/main.php(208): Director::direct('/admin/account-...', Object(DataModel))
#22 {main}
```

Again, if this is something that changed or something I may be doing wrong with the client maybe you could point me in the right direction, but if this is purely my issue or Podio's issue then kill the issue.

Thanks for the great product.

**Comment by daniel-sc** [comment]
Hi @johnBHGW 

First, I'd like to prevent potential confusion: this is about a field of type "category" (see https://developers.podio.com/doc/items ) with external id "tag-2" and not about regular "tags".

Could you provide the version of podio-php you are using (and if possible update to the latest release). 
Furthermore debug info from `Podio::setDebug(true)` (anonymized) might help.

**Comment by johnBHGW** [comment]
Hi @daniel-sc,
    I see where I got that switched out. Thank you. I will look to make sure that it is not affecting the value of the ID i am trying to use, although I don't think it would.
    Also the version of the Podio-PHP library that we are using is 4.3, and lastly the debugging option is setup in my _config.php file like so. 
   Podio::setup(PODIO_CLIENT_ID, PODIO_CLIENT_SECRET, [
    'session_manager' => Injector::inst()->get(PodioSession::class),
    'curl_options' => array(),
    Podio::set_debug(true)
]);
Did it not produce what you would have expected? I have tried it both with the file option and without. the stack trace I included was with it set to true.

**Comment by daniel-sc** [comment]
Hi @johnBHGW 
Could you check if the option id is correct (and not deleted) by fetching the app structure (https://developers.podio.com/doc/applications/get-area-22349)?

**Comment by johnBHGW** [comment]
The GET request that you provided(developers.podio.com/doc/applications/get-area-22349) using the ID of my application spits out JSON that looks fine. The option ID looks correct if I am looking at the right thing. The field that I am trying to add to is a category field labeled Tags, with an external_id of tags-2. There does not seem to be a single option ID for the field in question, there are ID's for each option in the array of choices for the fields and they are correct. 

  "url_label": "customers",
  "app_id": 11111111,
  "layouts": {
    "badge": {
      "default": true,
      "fields": {
        "details_1": {
          "type": "field",
          "id": 192188368
        },
        "footer_1": {
          "type": "virtual",
          "id": "created_on"
        },
        "header": {
          "type": "field",
          "id": 192192192192
        },
        "footer_2": {
          "type": "virtual",
          "id": "created_by"
        },
        "details_2": {
          "type": "field",
          "id": 193193193193
        },
        "content": {
          "type": "field",
          "id": 194194194
        },
        "details_3": {
          "type": "field",
          "id": 195195195
        },
        "footer_3": {
          "type": "virtual",
          "id": "comment_count"
        }
      }
    },
    "relationship": {
      "default": true,
      "fields": {
        "details_4": null,
        "details_3": {
          "type": "field",
          "id": 199199199
        },
        "details_1": {
          "type": "field",
          "id": 192188368
        },
        "details_2": {
          "type": "field",
          "id": 198198198198
        },
        "header": {
          "type": "field",
          "id": 197197197
        }
      }
    },
    "card": {
      "default": true,
      "fields": {
        "content": {
          "type": "field",
          "id": 196196196
        },
        "details_3": {
          "type": "field",
          "id": 192188367
        },
        "details_1": {
          "type": "field",
          "id": 195195195
        },
        "details_2": {
          "type": "field",
          "id": 191191191
        },
        "header": {
          "type": "field",
          "id": 192192192
        }
      }
    },
    "badge_v2": {
      "default": true,
      "fields": {
        "details_1": {
          "type": "field",
          "id": 192192192
        },
        "footer_1": {
          "type": "virtual",
          "id": "created_on"
        },
        "header": {
          "type": "field",
          "id": 192192192
        },
        "footer_2": {
          "type": "virtual",
          "id": "created_by"
        },
        "details_2": {
          "type": "field",
          "id": 192192192
        },
        "content": {
          "type": "field",
          "id": 192188373
        },
        "details_3": {
          "type": "field",
          "id": 192192192
        },
        "footer_3": {
          "type": "virtual",
          "id": "comment_count"
        }
      }
    }
  },
  "owner": {
    "user_id": 499999,
    "space_id": null,
    "image": {
      "hosted_by": "podio",
      "hosted_by_humanized_name": "Podio",
      "thumbnail_link": "https://gravatarlink.com",
      "link": "https://gravatarlink.com",
      "file_id": 961227428,
      "external_file_id": null,
      "link_target": "_blank"
    },
    "profile_id": 192192192,
    "org_id": null,
    "link": "https://podio.com/users/4956834",
    "avatar": 192192192,
    "type": "user",
    "last_seen_on": "2020-10-29 15:23:41",
    "name": "Steve D Kummer"
  },
  "subscribed": false,
  "integration": null,
  "config": {
    "allow_edit": true,
    "tasks": [

    ],
    "yesno": false,
    "silent_creates": false,
    "yesno_label": null,
    "thumbs": false,
    "app_item_id_padding": 1,
    "show_app_item_id": false,
    "default_view": "badge",
    "allow_tags": false,
    "item_name": "Customers",
    "allow_attachments": true,
    "allow_create": true,
    "app_item_id_prefix": "",
    "disable_notifications": false,
    "fivestar": false,
    "thumbs_label": null,
    "type": "contact",
    "rsvp": false,
    "description": null,
    "usage": null,
    "fivestar_label": null,
    "approved": false,
    "icon": "55.png",
    "allow_comments": true,
    "name": "Customers",
    "icon_id": 55,
    "calendar_color_category_field_id": null,
    "silent_edits": false,
    "rsvp_label": null,
    "external_id": null
  },
  "status": "active",
  "default_view_id": null,
  "link_add": "https://podio.com/testsitecom/test/test",
  "mailbox": "customers.b3d20393",
  "is_default": false,
  "link": "https://podio.com/https:/podio.com/testsitecom/test/test/apps/customers",
  "url_add": "https://podio.comhttps:/podio.com/testsitecom/test/test/apps/customers/items/new",
  "sharefile_vault_url": null,
  "original_revision": 6,
  "rights": [
    "view_structure",
    "report_visualization",
    "add_task",
    "subscribe",
    "reference",
    "share",
    "add_item",
    "install",
    "add_hook",
    "update",
    "export",
    "view",
    "delete",
    "manage_public_views",
    "add_integration",
    "add_advanced_flow",
    "add_flow",
    "add_widget"
  ],
  "url": "https://podio.com/edgepharmacycom/bhg-sandbox/apps/customers",
  "fields": [
    {
      "status": "active",
      "type": "text",
      "field_id": 192192192,
      "label": "First Name",
      "config": {
        "default_value": null,
        "unique": false,
        "description": null,
        "hidden_create_view_edit": false,
        "required": false,
        "mapping": "contact_name",
        "label": "First Name",
        "visible": true,
        "delta": 0,
        "hidden": false,
        "settings": {
          "format": "plain",
          "size": "small"
        }
      },
      "external_id": "name"
    },
    {
      "status": "active",
      "type": "text",
      "field_id": 192192192,
      "label": "Last Name",
      "config": {
        "default_value": null,
        "unique": false,
        "description": null,
        "hidden_create_view_edit": false,
        "required": false,
        "mapping": null,
        "label": "Last Name",
        "visible": true,
        "delta": 1,
        "hidden": false,
        "settings": {
          "format": "html",
          "size": "large"
        }
      },
      "external_id": "last-name"
    },
    {
      "status": "active",
      "type": "category",
      "field_id": 192192192,
      "label": "Tags",
      "config": {
        "default_value": null,
        "unique": false,
        "description": null,
        "hidden_create_view_edit": false,
        "required": false,
        "mapping": null,
        "label": "Tags",
        "visible": true,
        "delta": 2,
        "hidden": false,
        "settings": {
          "multiple": true,
          "options": [
            {
              "status": "active",
              "text": "Epi/Lido",
              "id": 1,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Aesthetics",
              "id": 2,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Alberta",
              "id": 3,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Allergy",
              "id": 4,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Anesthesiology",
              "id": 5,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "BC",
              "id": 6,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "BLT Cream",
              "id": 7,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Boric Acid Suppository",
              "id": 8,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Brilliant Blue",
              "id": 9,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Buffered Lidocaine",
              "id": 10,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Canada",
              "id": 11,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Canada Hospital",
              "id": 12,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Cantharidin",
              "id": 13,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Cardiology",
              "id": 14,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Chiropractor",
              "id": 15,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Clinic",
              "id": 16,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Clinical Trial",
              "id": 17,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Combo Drops",
              "id": 18,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "CSF Powder",
              "id": 19,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Dentistry",
              "id": 20,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Dermatology",
              "id": 21,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Dexamethasone Injection",
              "id": 22,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Dibutyl Squaric Acid",
              "id": 23,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Dyclonine Rinse",
              "id": 24,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "EDTA",
              "id": 25,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Endodontist",
              "id": 26,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "ENT",
              "id": 27,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Epi 1:1,000",
              "id": 28,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Epi-Shugarcaine",
              "id": 29,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "ER",
              "id": 30,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Gastroenterology",
              "id": 31,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "HDFG",
              "id": 32,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Hematology",
              "id": 33,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Hospital",
              "id": 34,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "HyBlocks",
              "id": 35,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Imported",
              "id": 36,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Internal Medicine",
              "id": 37,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Isoproterenol",
              "id": 38,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "JCB",
              "id": 39,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "LDA",
              "id": 40,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "LET Gel",
              "id": 41,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Lipostat Plus",
              "id": 42,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "McBladder",
              "id": 43,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Methacholine",
              "id": 44,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Methotrexate",
              "id": 45,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Methylene Blue",
              "id": 46,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Mitomycin",
              "id": 47,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Mohs",
              "id": 48,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Moxifloxacin",
              "id": 49,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Nasal Solutions",
              "id": 50,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Naturopath",
              "id": 51,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "NB",
              "id": 52,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Neostigmine",
              "id": 53,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Neurology",
              "id": 54,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Newfoundland",
              "id": 55,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Nova Scotia",
              "id": 56,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "NS",
              "id": 57,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "OB/GYN",
              "id": 58,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Oncology",
              "id": 59,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Ontario",
              "id": 60,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Ophthalmology",
              "id": 61,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Orthodontics",
              "id": 62,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Orthopedics",
              "id": 63,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Pain Management",
              "id": 64,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Pathology",
              "id": 65,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Pediatrician",
              "id": 66,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Pharmacist",
              "id": 67,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Pharmacy",
              "id": 68,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Phenol",
              "id": 69,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Phenylephrine",
              "id": 70,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Physical Therapy",
              "id": 71,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Plastic Surgery",
              "id": 72,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Podiatry",
              "id": 73,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Primary Care",
              "id": 74,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Profound Gel",
              "id": 75,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Promethazine Gel",
              "id": 76,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Pulmonology",
              "id": 77,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Retina",
              "id": 78,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Rheumatology",
              "id": 79,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "ROI",
              "id": 80,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Saskatchewan",
              "id": 81,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Succinylcholine",
              "id": 82,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Surgery Center",
              "id": 83,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Tatoo",
              "id": 84,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Tonsil Fire Extinguisher",
              "id": 85,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Triamcinolone",
              "id": 86,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Trichloroacetic Acid",
              "id": 87,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Trypan Blue",
              "id": 88,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Urgent Care",
              "id": 89,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Urology",
              "id": 90,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Vancouver",
              "id": 91,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Veterinarian",
              "id": 92,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "VIHA",
              "id": 93,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Vitamin K",
              "id": 94,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Wart Removal",
              "id": 95,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Newsletter",
              "id": 96,
              "color": "DCEBD8"
            }
          ],
          "display": "inline"
        }
      },
      "external_id": "tags-2"
    },
    {
      "status": "active",
      "type": "category",
      "field_id": 192192192,
      "label": "How Did You Hear About Us",
      "config": {
        "default_value": null,
        "unique": false,
        "description": null,
        "hidden_create_view_edit": false,
        "required": false,
        "mapping": null,
        "label": "How Did You Hear About Us",
        "visible": true,
        "delta": 3,
        "hidden": false,
        "settings": {
          "multiple": false,
          "options": [
            {
              "status": "active",
              "text": "Web Search",
              "id": 1,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Web Advertisement",
              "id": 2,
              "color": "DDDDDD"
            },
            {
              "status": "active",
              "text": "Letter or Postcard in Mail",
              "id": 3,
              "color": "F7D1D0"
            },
            {
              "status": "active",
              "text": "Trade Show or Conference",
              "id": 4,
              "color": "D2E4EB"
            },
            {
              "status": "active",
              "text": "FDA 503B Outsourcing Website",
              "id": 5,
              "color": "F7F0C5"
            },
            {
              "status": "active",
              "text": "Referral",
              "id": 6,
              "color": "E1D8ED"
            },
            {
              "status": "active",
              "text": "Already a Customer",
              "id": 7,
              "color": "FFD5C2"
            },
            {
              "status": "active",
              "text": "Other",
              "id": 8,
              "color": "D1F3EC"
            }
          ],
          "display": "inline"
        }
      },
      "external_id": "how-did-you-hear-about-us"
    },
    {
      "status": "active",
      "type": "text",
      "field_id": 192192192,
      "label": "Title",
      "config": {
        "default_value": null,
        "unique": false,
        "description": null,
        "hidden_create_view_edit": false,
        "required": false,
        "mapping": "contact_job_title",
        "label": "Title",
        "visible": true,
        "delta": 4,
        "hidden": false,
        "settings": {
          "format": "plain",
          "size": "small"
        }
      },
      "external_id": "job-title"
    },
    {
      "status": "active",
      "type": "category",
      "field_id": 192192192,
      "label": "Category",
      "config": {
        "default_value": null,
        "unique": false,
        "description": null,
        "hidden_create_view_edit": false,
        "required": false,
        "mapping": null,
        "label": "Category",
        "visible": true,
        "delta": 5,
        "hidden": false,
        "settings": {
          "multiple": false,
          "options": [
            {
              "status": "active",
              "text": "Clinic",
              "id": 1,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "Hospital",
              "id": 2,
              "color": "DDDDDD"
            },
            {
              "status": "active",
              "text": "Surgery Center",
              "id": 3,
              "color": "F7D1D0"
            },
            {
              "status": "active",
              "text": "Other",
              "id": 4,
              "color": "D2E4EB"
            }
          ],
          "display": "inline"
        }
      },
      "external_id": "category"
    },
    {
      "status": "active",
      "type": "category",
      "field_id": 192192192,
      "label": "Subscribed to Newsletter",
      "config": {
        "default_value": null,
        "unique": false,
        "description": null,
        "hidden_create_view_edit": false,
        "required": false,
        "mapping": null,
        "label": "Subscribed to Newsletter",
        "visible": true,
        "delta": 6,
        "hidden": false,
        "settings": {
          "multiple": false,
          "options": [
            {
              "status": "active",
              "text": "Yes",
              "id": 1,
              "color": "DCEBD8"
            },
            {
              "status": "active",
              "text": "No",
              "id": 2,
              "color": "DDDDDD"
            }
          ],
          "display": "inline"
        }
      },
      "external_id": "subscribed-to-newsletter"
    },
    {
      "status": "active",
      "type": "tag",
      "field_id": 192192192,
      "label": "Company Name",
      "config": {
        "default_value": null,
        "unique": false,
        "description": null,
        "hidden_create_view_edit": false,
        "required": false,
        "mapping": "contact_organization",
        "label": "Company Name",
        "visible": true,
        "delta": 7,
        "hidden": false,
        "settings": null
      },
      "external_id": "organization"
    },
    {
      "status": "active",
      "type": "email",
      "field_id": 192192192,
      "label": "Email",
      "config": {
        "default_value": null,
        "unique": false,
        "description": null,
        "hidden_create_view_edit": false,
        "required": false,
        "mapping": "contact_email",
        "label": "Email",
        "visible": true,
        "delta": 8,
        "hidden": false,
        "settings": {
          "include_in_bcc": false,
          "include_in_cc": false,
          "possible_types": [
            "work",
            "home",
            "other"
          ]
        }
      },
      "external_id": "email-address"
    },
    {
      "status": "active",
      "type": "phone",
      "field_id": 192192192,
      "label": "Phone Number",
      "config": {
        "default_value": null,
        "unique": false,
        "description": null,
        "hidden_create_view_edit": false,
        "required": false,
        "mapping": "contact_phone",
        "label": "Phone Number",
        "visible": true,
        "delta": 9,
        "hidden": false,
        "settings": {
          "call_link_scheme": "callto",
          "possible_types": [
            "mobile",
            "work",
            "home",
            "main",
            "work_fax",
            "private_fax",
            "other"
          ]
        }
      },
      "external_id": "phone-number"
    },
    {
      "status": "active",
      "type": "location",
      "field_id": 192192192,
      "label": "Address",
      "config": {
        "default_value": null,
        "unique": false,
        "description": null,
        "hidden_create_view_edit": false,
        "required": false,
        "mapping": "contact_address",
        "label": "Address",
        "visible": true,
        "delta": 10,
        "hidden": false,
        "settings": {
          "structured": true,
          "has_map": true
        }
      },
      "external_id": "address"
    },
    {
      "status": "active",
      "type": "embed",
      "field_id": 192192192,
      "label": "Website",
      "config": {
        "default_value": null,
        "unique": false,
        "description": null,
        "hidden_create_view_edit": false,
        "required": false,
        "mapping": "contact_website",
        "label": "Website",
        "visible": true,
        "delta": 11,
        "hidden": false,
        "settings": null
      },
      "external_id": "website"
    },
    {
      "status": "active",
      "type": "text",
      "field_id": 192192192,
      "label": "Notes",
      "config": {
        "default_value": null,
        "unique": false,
        "description": null,
        "hidden_create_view_edit": false,
        "required": false,
        "mapping": "contact_notes",
        "label": "Notes",
        "visible": true,
        "delta": 12,
        "hidden": false,
        "settings": {
          "format": "html",
          "size": "large"
        }
      },
      "external_id": "notes"
    },
    {
      "status": "active",
      "type": "image",
      "field_id": 192192192,
      "label": "Photo",
      "config": {
        "default_value": null,
        "unique": false,
        "description": "Supported image types: .jpg .gif .png",
        "hidden_create_view_edit": false,
        "required": false,
        "mapping": "contact_image",
        "label": "Photo",
        "visible": true,
        "delta": 13,
        "hidden": false,
        "settings": {
          "allowed_mimetypes": [
            "image/png"
          ]
        }
      },
      "external_id": "photo"
    }
  ],
  "space_id": 664665663,
  "current_revision": 1,
  "original": 91id91id91id,
  "token": "8f01sampletokendata4831c8",
  "item_accounting_info": null

**Comment by daniel-sc** [comment]
Hi @johnBHGW 

Thanks got sharing the app structure. As far as I could see on my mobile, `tags-2` does not contain an option with id "97" - so the error from Podio seems correct. I suggest you check the constants `PODIO_ORGANIZATION_TYPE...` and double check all ids are actually present. 

Please post here if this resolves the issue.

**Comment by daniel-sc** [comment]
please reopen, if problem was not resolved
