### ISSUE TITLE
Images do not load with this library?

### ISSUE THREAD

**Issue by bonini81** [podio-community/podio-php#199]
Hi all, so images are considerred private from the Podio API, cause they do not load, once you grab data from the API, everything else does. I have seen other users having such issue, like on this post: https://stackoverflow.com/questions/58379704/how-to-get-public-access-to-files-or-images-from-podio-api-if-i-have-image-id-or   
Am i correct, or there is a way to load image from the API, looks like the only way to make images public from Podio is by using Globiflow which is a paid service, of course.
If there is a way to load images via the free API, let me know.
thanx

**Comment by daniel-sc** [comment]
Hi @bonini81 

Not sure what you want to accomplish. 

Images can be accessed via the api, but you need to be authorized (as for any api access).

If this is not directly related to the API client, please create a stackoverflow issue. 

Best Daniel

**Comment by bonini81** [comment]
Hi Daniel thanx for the reply. Well, yes the problem is related to the client API, not sure if Podio has changed its API usage rules lately for images (that is why other users here havent commented on it), cause checked on google that other users have the same problem lately while using the API client from Podio (stackoverflow article i passed before), that Podio has made images from Podio Private (not Public even with API authentication), the rest of data can be accessed by the API, like on ths site which i got the Podio PHP library installed, https://structuredig.com/test-podio/  As you can see data is transferred from API to my site but only images do not load on the browser, like this Podio image link from my podio app, https://files.podio.com/1003026125/extra_large   when you view that image on the browser it redirects you to Podio to login, and the same happens on the site i just passed you, images do not load, even if i am authenticated by the API, heard Globiflow has a feature to make Podio images public, so on forums that seems to be the solution for images to load on third party sites, update to podio premium to be able to use Globiflow.  So that is my question basically, wether more users have had the same problem of not been able to view images from Podio, of course, even if you are authenticated via the API  (using this Podio PHP libray) from their sites.

**Comment by daniel-sc** [comment]
Hi @bonini81 
probably there is something wrong with your setup.
Can you try to use the latest version of this library and run the following as a CLI program to check if this works?

```php
\Podio::setup($clientId, $clientSecret);
\Podio::authenticate_with_password($podioUser, $podioPassword);

\Podio::set_debug(true, 'stdout');

$file = \PodioFile::get('YOUR FILE ID');
$raw = $file->get_raw('extra_large');
file_put_contents($file->name, $raw);
```

**Comment by bonini81** [comment]
Hi, well i am using it in a Wordpress site, not sure if can using as a CLI program in there, i all update the library and try using your suggestions to see if images do load and i all get back to you guys. Anyways, i saw that other Podio users had a similar issues with images lately, so i thought images would not load with this libray as well. 
Thanx

**Comment by daniel-sc** [comment]
Yes please check if you can test it. Please share as well your actual code and the version used.

**Comment by daniel-sc** [comment]
Closing this as stale - please reach out if the issue presists!
