### ISSUE TITLE
[BUG] Using an expired token throws PodioConnectionError without attempt to refresh token

### ISSUE THREAD

**Issue by carlfredrikhero** [podio-community/podio-php#211]
With Guzzle the try catch section catches to many errors.

https://github.com/podio-community/podio-php/blob/e6dec1c2793dcb3ab72baf917a0483206f5ec3ff/lib/Podio.php#L261-L282

A `401` error indicates that the access token is expired and the code on line 307-329 tries to mitigate that error by refreshing the token and retry the original request.

https://github.com/podio-community/podio-php/blob/e6dec1c2793dcb3ab72baf917a0483206f5ec3ff/lib/Podio.php#L307-L329

With the new try catch however, that part is never executed as the script throws PodioConnectionError instead.

I believe we should catch the Guzzle exception but then pass on the status code and body to the `$response` object so that the script can deal with the response as it used to.

**Comment by carlfredrikhero** [comment]
I would gladly send a pull request for the fix but I'd like to know if there were any deliberate reason to throw the PodioConnectionError that early?

**Comment by daniel-sc** [comment]
Hi @carlfredrikhero 

thanks for bringing this up!

If I understand correctly, the cleaner fix might be to supply the request option `'http_errors' => false` (see https://docs.guzzlephp.org/en/stable/request-options.html#http-errors ) as indicated in L280? 
(Either at request level or at client creation)

Could you try this? (A PR would be very welcome :) )

Best, Daniel

**Comment by carlfredrikhero** [comment]
Sure @daniel-sc, I agree that your suggestion is a lot cleaner. I will try it out!

**Comment by carlfredrikhero** [comment]
It is working as expected. Should we introduce a new option to the Podio class or change the default behavior (without any way to toggle the option)?

For me I think it's fine to change the default since it is in fact going back to how it used to work. But then maybe someone has refactored his/her code to the new PodioConnectionError behavior.

**Comment by daniel-sc** [comment]
I'd consider this a bug, as this change was neither communicated nor intended.

So for me, making it the new default at client creation would be preferred. Any user can still fiddle with `Podio::$http_client` if needed.

**Comment by carlfredrikhero** [comment]
> Any user can still fiddle with `Podio::$http_client` if needed.

Right, I'll make a PR.

**Comment by carlfredrikhero** [comment]
Thanks @daniel-sc for the help with Guzzles Request option!

**Comment by daniel-sc** [comment]
Thanks @carlfredrikhero for putting in the effort!
