### ISSUE TITLE
New item is not created

### ISSUE THREAD

**Issue by wasimakaram** [podio-community/podio-php#213]
Hi 
I want to create a new item but it failed
My Code is given below

```
<?php
require __DIR__ . '/vendor/autoload.php';
require_once("invoice_app_credentails.php");
Podio::setup(CLIENT_ID, CLIENT_SECRET);
Podio::authenticate_with_app(APP_ID, APP_TOKEN);
$fields = new PodioItemFieldCollection(array(
  new PodioTextItemField(array("external_id" => "title", "values" => "Wasim Akram")),
  new PodioTextItemField(array("external_id" => "email-address", "values" => "info@wasimamjad.com")),
  new PodioTextItemField(array("external_id" => "invoice-number", "values" => "123456")),
));
$item = new PodioItem(array(
  'app' => new PodioApp(APP_ID), // Attach to app with 
  'fields' => $fields
));
$response = $item->save();
echo "<pre>";print_r($response);die;
```

It gives me the following error
**Fatal error: Uncaught PodioMissingRelationshipError: "Item is missing relationship to app" Request URL: Stack Trace: #0 /home/customer/www/measuredsurveyexperts.com/public_html/Podio_Xero_integration/create_podio_invoice.php(24): PodioItem->save() #1 {main} thrown in /home/customer/www/measuredsurveyexperts.com/public_html/Podio_Xero_integration/models/PodioItem.php on line 78**

Actually when I want to create an object of PodioApp class with APP_ID and assign that object to PodioItem class. The APP_ID is assigned properly.

When I put APP_ID hardcoded in the file models->PodioItem.php on line number 71, then it's working fine. My hardcoded id is given below

if ($this->id) {
            return self::update($this->id, $json_attributes, $options);
        } else {
            $this->app->id = 26545976;
            if ($this->app && $this->app->id) {
                $new = self::create($this->app->id, $json_attributes, $options);
                $this->item_id = $new->item_id;
                return $this;
         }

I think there is an issue in the library. Can you please help me?
Thanks

**Comment by daniel-sc** [comment]
Hi @wasimakaram ,

On first glance, it looks like you found a bug.

Could you tell which version of PHP and of this library you are using?

Best, Daniel

**Comment by daniel-sc** [comment]
Hi @wasimakaram 

I could reproduce this and found the solution: You need to make sure `APP_ID` is a number (and _not_ a string). 
E.g. `define('APP_ID', 123456789);`

Let me know if this does not work!

Best, Daniel
