### ISSUE TITLE
Correction to Podio::post with file upload option needed

### ISSUE THREAD

**Issue by mgithens** [podio-community/podio-php#215]
In https://github.com/podio-community/podio-php/blob/master/lib/Podio.php
at line 222 and 223 which contains:

              'contents' => fopen($options['upload'], 'r'),
              'filename' => $options['upload']

This should be changed to:

              'contents' => fopen($attributes['filename'], 'r'),
              'filename' => $attributes['filename']

since the Podio::post method (in https://github.com/podio-community/podio-php/blob/master/models/PodioFile.php at line 61) is passing "array('upload' => true," which is a boolean of "true" and causes the fopen($options['upload'], 'r') (which contains a value of "true") to produce an exception of "fopen(1): failed to open stream: No such file or directory" since fopen expects a filename as it's first parameter.

**Comment by daniel-sc** [comment]
Hi @mgithens 
thanks for posting this and doing the research for this problem!
Would you like to provide a PR for this as well?
Best, Daniel
