### ISSUE TITLE
podio php api not working anymore on php 8.0.17

### ISSUE THREAD

**Issue by jespyxis** [podio-community/podio-php#218]
Everything was working and still works locally with version 7. However, with version 8.0.17 require_once 'podio-php/PodioAPI.php'; fails, I get HTTP 500 response. Further investigation has shown that the following 👍 

require_once 'lib/PodioError.php';

and

require_once 'models/PodioItemField.php';

are causing the problem. 

I am using the same PodioAPI.php that I was using with 7.0. Perhaps someone can help on this...

**Comment by daniel-sc** [comment]
Hi @jespyxis 

are you using the suggested setup with [composer](https://getcomposer.org/)?
In that case you should `require __DIR__ . '/vendor/autoload.php';`..
If not, I'd highly recommend using composer :)

Best Daniel

**Comment by daniel-sc** [comment]
@Christoph111 yes - this is only usable with composer. There is plenty documentation online on how to use composer, so I won't go into details - for a start: https://getcomposer.org
