### ISSUE TITLE
Please upgrade composer dependency "kint-php/kint ^3.2" to at least v4

### ISSUE THREAD

**Issue by Martin-4Spaces** [podio-community/podio-php#221]
I'm running into conflicts when using podio-php v5 and above, because of the requirement to kint ^3.2. Other composer libraries i'm, using is depending on kint ^4.2
kint v4 was released in 2021, so i think it is fair for podio-php to look at an upgrade of the requirement. 
Thank you!

**Comment by daniel-sc** [comment]
sounds reasonable to me - would you like to create a PR for this?

**Comment by Martin-4Spaces** [comment]
@daniel-sc Done.
Will you take a look?
