### ISSUE TITLE
/podio-community/podio-php/lib/error/PodioError.php missing `public $request` declaration

### ISSUE THREAD

**Issue by mgithens** [podio-community/podio-php#223]
I've noticed that I was getting occasional errors from the get_raw() function. I still need to dig further to get to the root of the problem but I did notice a couple adjustments to consider for the [PodioError.php](https://github.com/podio-community/podio-php/blob/master/lib/error/PodioError.php) file which I've highlighted below. 

```
$file = \PodioFile::get($file_id);
$file_content = $file->get_raw();
```

**Message:** Trying to access array offset on value of type null
**File:** /public_html/vendor/podio-community/podio-php/lib/error/PodioError.php
**Line:** 13
**Trace:**
Array ( 
  [0] => Array ( [file] => /public_html/vendor/laravel/lumen-framework/src/Concerns/RegistersExceptionHandlers.php
                          [line] => 47 
                          [function] => handleError 
                          [class] => Laravel\Lumen\Application 
                          [type] => -> ) 
  [1] => Array ( [file] => /public_html/vendor/podio-community/podio-php/lib/error/PodioError.php
                         [line] => 13 
                         [function] => Laravel\Lumen\Concerns\{closure} 
                         [class] => Laravel\Lumen\Application [type] => -> ) 
[2] => Array ( [file] => /public_html/vendor/podio-community/podio-php/lib/Podio.php
                        [line] => 346 
                        [function] => __construct 
                        [class] => PodioError 
                        [type] => -> ) 
[3] => Array ( [file] => /public_html/vendor/podio-community/podio-php/lib/Podio.php
                        [line] => 355 
                        [function] => request 
                        [class] => Podio 
                        [type] => :: ) 
[4] => Array ( [file] => /public_html/vendor/podio-community/podio-php/models/PodioFile.php
                        [line] => 40 
                        [function] => get 
                        [class] => Podio 
                        [type] => :: ) 
[5] => Array ( [file] => /public_html/app/Http/Controllers/AssignmentController.php
                        [line] => 1427 
                        [function] => get_raw 
                        [class] => PodioFile 
                       [type] => -> ) 
[6] => Array ( [file] => /public_html/vendor/illuminate/container/BoundMethod.php
                        [line] => 36 
                        [function] => downloadFile 
                        [class] => App\Http\Controllers\AssignmentController

I took a quick look at [PodioError.php](https://github.com/podio-community/podio-php/blob/master/lib/error/PodioError.php) and notice it's missing the declaration for the public $request attribute.

`<?php

class PodioError extends Exception
{
    public $body;
    public $status;
    public $url;
    **public $request;  // SHOULDN'T THIS BE DECLARED**
    public function __construct($body, $status, $url)
    {
        $this->body = json_decode($body, true);
        $this->status = $status;
        $this->url = $url;
        **$this->request = $this->body['request']; // ALSO, WOULD IT BE GOOD TO ADD "?? null; IN CASE 'request' DOESN'T EXIST?"**
        parent::__construct(get_class($this), 1, null);
    }

    public function __toString()
    {
        $str = $str = get_class($this);
        if (!empty($this->body['error_description'])) {
            $str .= ': "'.$this->body['error_description'].'"';
        }
        $str .= "\nRequest URL: ".$this->request['url'];
        if (!empty($this->request['query_string'])) {
            $str .= '?'.$this->request['query_string'];
        }
        if (!empty($this->request['body'])) {
            $str .= "\nRequest Body: ".json_encode($this->request['body']);
        }

        $str .= "\n\nStack Trace: \n".$this->getTraceAsString();
        return $str;
    }
}
`

**Comment by daniel-sc** [comment]
@mgithens Did you get to the root of the problem? For your suggestions: would you mind making a PR?

**Comment by mgithens** [comment]
@daniel-sc I have not yet had a chance to get to the root of the problem but I did go ahead and make a PR.

**Comment by daniel-sc** [comment]
@mgithens Hm - I did not find any PR - can you double check?

**Comment by mgithens** [comment]
@daniel-sc Sorry, I'm not sure if they were added correctly. Please advise if I missed something. Thanks

Update PodioError.php
Added the missing public $request var that is used without being declared.
https://github.com/mgithens/podio-php/commit/481f6503ebaa6fbf644c002d692bd097dccb75d4

Update PodioError.php
If $this->body['request'] doesn't exist then set $this->request to null
https://github.com/mgithens/podio-php/commit/48ab678c80ce21e47cb9f933e7e379f37987f817

**Comment by daniel-sc** [comment]
@mgithens You need to create a PR from these commits - see eg https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request?tool=webui

**Comment by mgithens** [comment]
@daniel-sc Sorry about that. I've added 3 PRs.
