### ISSUE TITLE
PHP 8.1 ArrayAccess Issue

### ISSUE THREAD

**Issue by sollemar** [podio-community/podio-php#224]
Return type of PodioCollection::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

podio-community/podio-php/lib/PodioCollection.php, Line 95

Please fix this issue asap.

**Comment by daniel-sc** [comment]
Hi @sollemar thanks for reporting this!

This lib is _not_ supported by Podio and relies solely on voluntary contributions from the community. Would you like to make a PR for resolving this problem? (And possibly include further similar problems?)

**Comment by bbanuri** [comment]
@daniel-sc I wanted to give this one a try. Here is my [PR](https://github.com/podio-community/podio-php/pull/229)

**Comment by bbanuri** [comment]
@daniel-sc I think this issue can be closed now.

**Comment by bbanuri** [comment]
@daniel-sc Glad I was able to take care of it. I would like to contribute wherever I am able to.

**Comment by sollemar** [comment]
Thanks for the fix!
