### ISSUE TITLE
Create / save field to an Item

### ISSUE THREAD

**Issue by simplenotezy** [podio-community/podio-php#87]
I loop through a collection of items, and for every item, I wish to either update the current field, or add it if it does not exist, however, I have not found an easy way to do this through the documentation.

Current approach:

```
$items = PodioItem::filter($this->options['app_id']);

foreach($items as $item) {
    $field = ($item->fields["my-field"]) ? $item->fields["my-field"] : new PodioItemField("my-field");
    $field->values = rand(1,9);
    $field->save();
}
```

Generates following error:

```
Fatal error: Uncaught PodioMissingRelationshipError: "Field is missing relationship to item
```

Is there another easier way? If not, how do I assign the relationship?

**Comment by hphuhtin** [comment]
Instead of creating a new field item you should just set the value of the field in an existing item. See http://podio.github.io/podio-php/fields/

**Comment by canfiax** [comment]
Can you show an example to my first added code?

**Comment by hphuhtin** [comment]
Can you clarify your intent, do you mean by "if it does not exist" - how would you get to a situation where a field does not exist (as opposed, to having no value)?

**Comment by hphuhtin** [comment]
From what you describe I wonder if you are trying to change the app structure via API? If so, then you should use PodioAppField::create( $app_id, $attributes = array() ); instead of creating a new ItemField object. But maybe I just don't understand what you are trying to do.

**Comment by hphuhtin** [comment]
I think I understand your case. A field that is has not value set is not returned with the item, sorry about my first confusion. Since you add the field to the item's PodioItemFieldCollection ($item->fields), have you tried just $item->save instead of $field->save?

**Comment by daniel-sc** [comment]
Closed as unactive, please reopen if problem persists.
