### ISSUE TITLE
Non-static Podio class

### ISSUE THREAD

**Issue by daniel-sc** [podio-community/podio-php#90]
Hi there,

for more fine grained control it would good if the API could be accessed in a non-static way. Especially for unit testing/mocking this is a must.

As a first shot I created: https://github.com/daniel-sc/podio-php/commit/d7ca0e4985a079f8cb5349df9f8c6bc023ad6fd6 

Do you think that's feasible?

greets, Daniel

**Comment by headdetect** [comment]
I've actually started an implementation of a nonstatic Podio library. It's specifically for the laravel framework, but if you like it, I can abstract it out. It has a bunch of other changes too, but I feel it's easier to use. https://github.com/techegos/laravel5-podio we'd appreciate any feedback if you do end up using it.

**Comment by daviferreira** [comment]
Hey guys, nice work. I would love to have both, actually, a non-static version and a laravel specific version. I'm no Laravel expert, but I think it would be great. What do you guys think, can we come up with a plan? Maybe wait for more people to jump in?

Cheers!

**Comment by carlfredrikhero** [comment]
While a non-static version is very much appreciated ( I think the static Podio PHP Library was modelled after the Python library ) I really want the library to stay framework independant. If a framework optimized version is needed, it should stay as a separate repo.

**Comment by daviferreira** [comment]
Yeah, totally agree, what I mean is like to have a PodioLaravel on this repo. But sutre, it can also be a different repo, we will still of course have a "pure" php version of the library :)

**Comment by daviferreira** [comment]
Also ping @jakubboucek, @NickIvanter
